version: "3.9"
services:
  backend:
    container_name: 'backend'
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file: backend/.env
    networks:
      - back
      - default
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    container_name: 'frontend'
    build:
      context: ./frontend
    ports:
      - "8080:80"
    restart: unless-stopped

  postgres:
    container_name: 'database'
    image: postgres:alpine
    env_file: .env.db
    networks:
      - back
      - default
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready  -U student -d kupipodariday" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  pgadmin:
    image: dpage/pgadmin4:7.2
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "pguser@pg.com"
      PGADMIN_DEFAULT_PASSWORD: "qwerty"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    networks:
      - back
      - default

networks:
  back:
    driver: bridge
    internal: true

volumes:
  db_data:
